services:
  web:
    image: gaabs16/gerador_saudacoes:1.6
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - ms-pessoas-aleatorias
      - ms-saudacoes-aleatorias
    networks:
      - backend

  ms-pessoas-aleatorias:
    image: gaabs16/ms-pessoas-aleatorias:1.0
    ports:
      - "8000:8000"
    networks:
      - backend

  ms-saudacoes-aleatorias:
      image: gaabs16/ms-saudacoes-aleatorias:1.0
      ports:
      - "8080:8080"
      networks:
        - backend

networks:
  backend: {}